"""Prompt templates for the AIOps agent."""

from .diagnostic import (
    DIAGNOSTIC_SYSTEM_PROMPT,
    FINAL_SUMMARY_SYSTEM_PROMPT,
    FINAL_SUMMARY_HUMAN_TEMPLATE,
)

__all__ = [
    "DIAGNOSTIC_SYSTEM_PROMPT",
    "FINAL_SUMMARY_SYSTEM_PROMPT",
    "FINAL_SUMMARY_HUMAN_TEMPLATE",
]
