{
 "title": "PromGraf MLOps - Model",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Distribution by Category",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(category) (predictions_by_category_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Input Text Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(input_text_length_chars_sum[1h]) / (rate(input_text_length_chars_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Accuracy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy_score * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Prediction Confidence",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(prediction_confidence_score_sum[1h]) / (rate(prediction_confidence_score_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predict avg Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_request_duration_seconds_sum{endpoint=\"/predict\"}[1h]) / (rate(api_request_duration_seconds_count{endpoint=\"/predict\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision by category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_precision_score", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "F1 by category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_f1_score", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Recall by category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_recall_score", "legendFormat": "{{category}}" }
   ]
  }
 ]
}